### ISSUE TITLE
[Feature Request] Proxy scenes list

### ISSUE THREAD

**Issue by zendorx** [britzl/extension-scene-graph#1]
It would be handy to have opportunity to get list of all loaded proxy scenes and get dump by its id. For now it requires to add script for every proxy scene and call dump from it.

**Comment by zendorx** [comment]
It seems that graph.dump() returns main collection dump always even if call it from proxy collection

**Comment by britzl** [comment]
> It seems that graph.dump() returns main collection dump always even if call it from proxy collection

Yes, you always get the entire screen graph from the bootstrap collection down to every leaf node. If you have loaded collection proxies they will also be included in the graph as children to the collection proxy. I added a collection proxy to the example project included with this extension.
